[package]
name = "ground_station"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
derive_builder = "0.11.2"
eframe = "0.18.0"
egui = "0.18.1"
enum-iterator = "1.1.3"
env_logger = "0.9.0"
log = "0.4.17"
parse-display = "0.5.5"
